"use client";
import { useEffect, useMemo, useState } from "react";
import { supabaseBrowser } from "@/lib/supabase-browser";
import type { User } from "@supabase/supabase-js";
import "./admin.css";

type Booking = { stall_id: string; status: "hold" | "booked"; company: string | null; contact: string | null; email: string | null; requested_at: string | null };

export default function AdminPage() {
  const [user, setUser] = useState<User | null>(null), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [bookings, setBookings] = useState<Booking[]>([]), [message, setMessage] = useState(""), [loading, setLoading] = useState(true), [busy, setBusy] = useState("");
  async function load() {
    setLoading(true); const { data: session } = await supabaseBrowser.auth.getSession(); setUser(session.session?.user ?? null);
    if (!session.session) return setLoading(false);
    const response = await fetch("/api/admin/bookings", { headers: { Authorization: `Bearer ${session.session.access_token}` }, cache: "no-store" }); const data = await response.json();
    if (!response.ok) setMessage(data.message ?? "Access denied."); else setBookings(data.bookings ?? []); setLoading(false);
  }
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  async function signIn(event: React.FormEvent) { event.preventDefault(); setMessage(""); setLoading(true); const { error } = await supabaseBrowser.auth.signInWithPassword({ email, password }); if (error) { setMessage(error.message); setLoading(false); return; } await load(); }
  async function changeStatus(stallId: string, status: "booked" | "hold") { setBusy(stallId); setMessage(""); const { data } = await supabaseBrowser.auth.getSession(); const response = await fetch("/api/admin/bookings", { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${data.session?.access_token}` }, body: JSON.stringify({ stallId, status }) }); if (!response.ok) setMessage((await response.json()).message ?? "Could not update booking."); else setMessage(`${stallId} is now ${status}.`); setBusy(""); await load(); }
  const holds = useMemo(() => bookings.filter((b) => b.status === "hold"), [bookings]), confirmed = useMemo(() => bookings.filter((b) => b.status === "booked"), [bookings]);
  if (!user) return <main className="admin-login"><section className="login-panel"><div className="admin-mark">75<span>IPC</span></div><p className="admin-kicker">Exhibition operations</p><h1>Welcome back.</h1><p className="admin-intro">Sign in to review stall requests and keep the Hall 1C booking desk current.</p><form onSubmit={signIn}><label>Email address<input type="email" placeholder="you@company.com" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>Password<input type="password" placeholder="Enter your password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label><button className="admin-primary" type="submit" disabled={loading}>{loading ? "Signing in…" : "Sign in to desk"}</button></form>{message && <p className="admin-error" role="alert">{message}</p>}<p className="login-foot">Authorised organisers only · Hall 1C</p></section><aside className="login-aside"><p className="admin-kicker">75th IPC PharmaExpo</p><h2>The floor, kept moving.</h2><p>Review requests, confirm exhibitors and keep availability honest for every visitor.</p></aside></main>;
  return <main className="admin-app"><header className="admin-top"><div className="admin-brand"><div className="admin-mark">75<span>IPC</span></div><div><p className="admin-kicker">Organiser desk</p><strong>Hall 1C operations</strong></div></div><div className="admin-account"><span>{user.email}</span><button onClick={() => void supabaseBrowser.auth.signOut().then(() => setUser(null))}>Sign out</button></div></header><section className="admin-content"><div className="admin-title"><div><p className="admin-kicker">Live booking control</p><h1>Stall requests</h1><p>Review provisional holds and confirm the exhibitors ready for the floor.</p></div><button className="refresh" onClick={() => void load()}>↻ Refresh</button></div><div className="admin-stats"><div><span>Awaiting review</span><strong>{holds.length}</strong><small>provisional holds</small></div><div><span>Confirmed</span><strong>{confirmed.length}</strong><small>booked stalls</small></div><div><span>Total activity</span><strong>{bookings.length}</strong><small>records in desk</small></div></div>{message && <p className="admin-notice">{message}</p>}<div className="admin-list"><div className="list-heading"><h2>Requests</h2><span>{bookings.length} records</span></div>{loading ? <div className="admin-empty">Loading requests…</div> : bookings.length === 0 ? <div className="admin-empty"><strong>No requests yet</strong><span>New stall holds will appear here automatically.</span></div> : bookings.map((booking) => <article className="booking-card" key={booking.stall_id}><div className="booking-id"><strong>{booking.stall_id}</strong><span className={`admin-status ${booking.status}`}>{booking.status}</span></div><div className="booking-details"><strong>{booking.company ?? "Unnamed company"}</strong><span>{booking.contact ?? "No contact name"}</span><a href={booking.email ? `mailto:${booking.email}` : undefined}>{booking.email ?? "No email provided"}</a></div><div className="booking-action"><button disabled={busy === booking.stall_id} onClick={() => void changeStatus(booking.stall_id, booking.status === "hold" ? "booked" : "hold")}>{busy === booking.stall_id ? "Updating…" : booking.status === "hold" ? "Confirm booking" : "Return to hold"}</button></div></article>)}</div></section></main>;
}
